//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.12 at 03:05:50 AM WET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://kholty.com/student", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.kholty.student;
